

r = {'Ain': 'fr-01',
 'Aisne': 'fr-02',
 'Allier': 'fr-03',
 'Alpes Maritimes': 'fr-06',
 'Alpes-Maritimes': 'fr-06',
 'Alpes de Haute Provence': 'fr-04',
 'Ardennes': 'fr-08',
 'Ardèche': 'fr-07',
 'Ariège': 'fr-09',
 'Aube': 'fr-10',
 'Aude': 'fr-11',
 'Aveyron': 'fr-12',
 'Bas-Rhin': 'fr-67',
 'Bouches du Rhône': 'fr-13',
 'Bouches-du-Rhône': 'fr-13',
 'Calvados': 'fr-14',
 'Cantal': 'fr-15',
 'Charente': 'fr-16',
 'Charente Maritime': 'fr-17',
 'Charente-Maritime': 'fr-17',
 'Cher': 'fr-18',
 'Corrèze': 'fr-19',
 'Corse du Sud': 'fr-2a',
 'Corse-du-Sud': 'fr-2a',
 'Corse': 'fr-2a',
 'Creuse': 'fr-23',
 "Côte d'Or": 'fr-21',
 "Côte-d'Or": 'fr-21',
 "Côtes d'Armor": 'fr-22',
 "Côtes-d'Armor": 'fr-22',
 'Deux Sèvres': 'fr-79',
 'Dordogne': 'fr-24',
 'Doubs': 'fr-25',
 'Drôme': 'fr-26',
 'Essonne': 'fr-91',
 'Eure': 'fr-27',
 'Eure et Loir': 'fr-28',
 'Eure-et-Loir': 'fr-28',
 'Finistère': 'fr-29',
 'Gard': 'fr-30',
 'Gers': 'fr-32',
 'Gironde': 'fr-33',
 'Haut Rhin': 'fr-68',
 'Haute Garonne': 'fr-31',
 'Haute Loire': 'fr-43',
 'Haute Marne': 'fr-52',
 'Haute-Marne': 'fr-52',
 'Haute Savoie': 'fr-74',
 'Haute-Savoie': 'fr-74',
 'Haute Saône': 'fr-70',
 'Haute Vienne': 'fr-87',
 'Haute-Vienne': 'fr-87',
 'Haute-Corse': 'fr-2b',
 'Hautes Alpes': 'fr-05',
 'Hautes-Alpes': 'fr-05',
 'Hautes Pyrénées': 'fr-65',
 'Hauts de Seine': 'fr-92',
 'Hauts-de-Seine': 'fr-92',
 'Hérault': 'fr-34',
 'Ille et Vilaine': 'fr-35',
 'Indre': 'fr-36',
 'Indre et Loire': 'fr-37',
 'Isère': 'fr-38',
 'Jura': 'fr-39',
 'Landes': 'fr-40',
 'Loir et Cher': 'fr-41',
 'Loire': 'fr-42',
 'Loire Atlantique': 'fr-44',
 'Loiret': 'fr-45',
 'Lot': 'fr-46',
 'Lot et Garonne': 'fr-47',
 'Lozère': 'fr-48',
 'Maine et Loire': 'fr-49',
 'Manche': 'fr-50',
 'Marne': 'fr-51',
 'Mayenne': 'fr-53',
 'Meurthe et Moselle': 'fr-54',
 'Meuse': 'fr-55',
 'Morbihan': 'fr-56',
 'Moselle': 'fr-57',
 'Nièvre': 'fr-58',
 'Nord': 'fr-59',
 'Oise': 'fr-60',
 'Orne': 'fr-61',
 'Paris': 'fr-75',
 'Pas de Calais': 'fr-62',
 'Puy de Dôme': 'fr-63',
 'Pyrénées Atlantiques': 'fr-64',
 'Pyrénées Orientales': 'fr-66',
 'Rhône': 'fr-69',
 'Sarthe': 'fr-72',
 'Savoie': 'fr-73',
 'Saône et Loire': 'fr-71',
 'Seine Maritime': 'fr-76',
 'Seine Saint-Denis': 'fr-93',
 'Seine et Marne': 'fr-77',
 'Somme': 'fr-80',
 'Tarn': 'fr-81',
 'Tarn et Garonne': 'fr-82',
 'Territoire de Belfort': 'fr-90',
 "Val d'Oise": 'fr-95',
 'Val de Marne': 'fr-94',
 'Var': 'fr-83',
 'Vaucluse': 'fr-84',
 'Vendée': 'fr-85',
 'Vienne': 'fr-86',
 'Vosges': 'fr-88',
 'Yonne': 'fr-89',
 'Yvelines': 'fr-78'}


if __name__ == "__main__":
  json_data = {}

  import pprint
  r_data = {}
  for k, v in json_data.items():
    r_data[v['name']] = k
  pprint.pprint(r_data)
