r = {'Afghanistan': 'af',
     'Albania': 'al',
     'Algeria': 'dz',
     'Angola': 'ao',
     'Antigua and Barbuda': 'ag',
     'Argentina': 'ar',
     'Armenia': 'am',
     'Australia': 'au',
     'Austria': 'at',
     'Azerbaijan': 'az',
     'Bahamas': 'bs',
     'Bangladesh': 'bd',
     'Barbados': 'bb',
     'Belarus': 'by',
     'Belgium': 'be',
     'Belize': 'bz',
     'Benin': 'bj',
     'Bhutan': 'bt',
     'Bolivia': 'bo',
     'Bosnia and Herzegovina': 'ba',
     'Botswana': 'bw',
     'Brazil': 'br',
     'Brunei Darussalam': 'bn',
     'Brunei': 'bn',
     'Bulgaria': 'bg',
     'Burkina Faso': 'bf',
     'Burundi': 'bi',
     'Cambodia': 'kh',
     'Cameroon': 'cm',
     'Canada': 'ca',
     'Cape Verde': 'cv',
     'Central African Republic': 'cf',
     'Chad': 'td',
     'Chile': 'cl',
     'China': 'cn',
     'Colombia': 'co',
     'Comoros': 'km',
     'Congo': 'cd',
     'Congo (Brazzaville)': 'cd',
     'Congo (Kinshasa)': 'cd',
     'Costa Rica': 'cr',
     "Cote d'Ivoire": 'ci',
     'Croatia': 'hr',
     'Cuba': 'cu',
     'Cyprus': 'cy',
     'Czech Republic': 'cz',
     'Denmark': 'dk',
     'Djibouti': 'dj',
     'Dominica': 'dm',
     'Dominican Republic': 'do',
     'Ecuador': 'ec',
     'Egypt': 'eg',
     'El Salvador': 'sv',
     'Equatorial Guinea': 'gq',
     'Eritrea': 'er',
     'Estonia': 'ee',
     'Ethiopia': 'et',
     'Falkland Islands': 'fk',
     'Fiji': 'fj',
     'Finland': 'fi',
     'France': 'fr',
     'French Guiana': 'gf',
     'French Polynesia': 'pf',
     'Gabon': 'ga',
     'Gambia': 'gm',
     'Georgia': 'ge',
     'Germany': 'de',
     'Ghana': 'gh',
     'Greece': 'gr',
     'Greenland': 'gl',
     'Grenada': 'gd',
     'Guatemala': 'gt',
     'Guinea': 'gn',
     'Guinea-Bissau': 'gw',
     'Guyana': 'gy',
     'Haiti': 'ht',
     'Honduras': 'hn',
     'Hungary': 'hu',
     'Iceland': 'is',
     'India': 'in',
     'Indonesia': 'id',
     'Iran': 'ir',
     'Iraq': 'iq',
     'Ireland': 'ie',
     'Israel': 'il',
     'Italy': 'it',
     'Jamaica': 'jm',
     'Japan': 'jp',
     'Jordan': 'jo',
     'Kazakhstan': 'kz',
     'Kenya': 'ke',
     'Kuwait': 'kw',
     'Kyrgyz Republic': 'kg',
     "Lao People's Democratic Republic": 'la',
     'Latvia': 'lv',
     'Lebanon': 'lb',
     'Lesotho': 'ls',
     'Liberia': 'lr',
     'Libya': 'ly',
     'Lithuania': 'lt',
     'Macedonia': 'mk',
     'Madagascar': 'mg',
     'Malawi': 'mw',
     'Malaysia': 'my',
     'Maldives': 'mv',
     'Mali': 'ml',
     'Malta': 'mt',
     'Mauritania': 'mr',
     'Mauritius': 'mu',
     'Mexico': 'mx',
     'Moldova': 'md',
     'Mongolia': 'mn',
     'Morocco': 'ma',
     'Mozambique': 'mz',
     'Myanmar': 'mm',
     'Namibia': 'na',
     'Nepal': 'np',
     'Netherlands': 'nl',
     'New Caledonia': 'nc',
     'New Zealand': 'nz',
     'Nicaragua': 'ni',
     'Niger': 'ne',
     'Nigeria': 'ng',
     'North Korea': 'kp',
     'Norway': 'no',
     'Oman': 'om',
     'Pakistan': 'pk',
     'Panama': 'pa',
     'Papua New Guinea': 'pg',
     'Paraguay': 'py',
     'Peru': 'pe',
     'Philippines': 'ph',
     'Poland': 'pl',
     'Portugal': 'pt',
     'Qatar': 'qa',
     'Reunion': 're',
     'Romania': 'ro',
     'Russian Federation': 'ru',
     'Russia': 'ru',
     'Rwanda': 'rw',
     'Saint Kitts and Nevis': 'kn',
     'Saint Lucia': 'lc',
     'Sao Tome and Principe': 'st',
     'Saudi Arabia': 'sa',
     'Senegal': 'sn',
     'Serbia': 'rs',
     'Seychelles': 'sc',
     'Sierra Leone': 'sl',
     'Slovakia': 'sk',
     'Slovenia': 'si',
     'Solomon Islands': 'sb',
     'Somalia': 'so',
     'South Africa': 'za',
     'South Korea': 'kr',
     'Spain': 'es',
     'Sri Lanka': 'lk',
     'Sudan': 'sd',
     'Suriname': 'sr',
     'Swaziland': 'sz',
     'Sweden': 'se',
     'Switzerland': 'ch',
     'Syrian Arab Republic': 'sy',
     'Taiwan': 'tw',
     'Taiwan*': 'tw',
     'Tajikistan': 'tj',
     'Tanzania': 'tz',
     'Thailand': 'th',
     'Timor-Leste': 'tl',
     'Togo': 'tg',
     'Trinidad and Tobago': 'tt',
     'Tunisia': 'tn',
     'Turkey': 'tr',
     'Turkmenistan': 'tm',
     'Uganda': 'ug',
     'Ukraine': 'ua',
     'United Arab Emirates': 'ae',
     'United Kingdom': 'gb',
     'United States of America': 'us',
     'US': 'us',
     'Uruguay': 'uy',
     'Uzbekistan': 'uz',
     'Vanuatu': 'vu',
     'Venezuela': 've',
     'Vietnam': 'vn',
     'Yemen': 'ye',
     'Zambia': 'zm',
     'Zimbabwe': 'zw'}
